//! Generated from interfaces/doc-html.json.
//! Regenerate with `cargo run --locked -p nepl3-tools -- doc-html --write`.
//! Registers structural shapes; named semantic constraints require their owning validators.

#[rustfmt::skip]
pub fn descriptor(budget: &mut nepl3_core::budget::Budget) -> Result<super::SchemaDescriptor, super::SchemaError> {
budget.charge(nepl3_core::budget::Resource::AllocationUnits, (339usize + 5 * core::mem::size_of::<super::NamedType>() + 11 * core::mem::size_of::<super::FieldDescriptor>() + 3 * core::mem::size_of::<super::VariantDescriptor>() + 2 * core::mem::size_of::<super::TypeDescriptor>()) as u64)?;
budget.charge(nepl3_core::budget::Resource::Work, 360)?;
Ok(super::SchemaDescriptor { package: "nepl3.doc.html".into(), revision: 1, types: alloc::vec![super::NamedType { name: "ElementOrigin".into(), shape: super::TypeShape::Record { fields: alloc::vec![super::FieldDescriptor { name: "element".into(), ty: super::TypeDescriptor::U64 },super::FieldDescriptor { name: "node".into(), ty: super::TypeDescriptor::U64 }] }, constraints: alloc::vec![] },
super::NamedType { name: "LocalHtmlRequest".into(), shape: super::TypeShape::Record { fields: alloc::vec![super::FieldDescriptor { name: "document".into(), ty: super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.doc".into(), revision: 1, name: "DocumentSyntax".into() }) },super::FieldDescriptor { name: "options".into(), ty: super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.doc.html".into(), revision: 1, name: "RenderOptions".into() }) }] }, constraints: alloc::vec![] },
super::NamedType { name: "ParallelMode".into(), shape: super::TypeShape::Variant { variants: alloc::vec![super::VariantDescriptor { name: "Columns".into(), fields: alloc::vec![] },super::VariantDescriptor { name: "Rows".into(), fields: alloc::vec![] },super::VariantDescriptor { name: "Single".into(), fields: alloc::vec![super::FieldDescriptor { name: "language".into(), ty: super::TypeDescriptor::Text },super::FieldDescriptor { name: "fallbacks".into(), ty: super::TypeDescriptor::List(alloc::boxed::Box::new(super::TypeDescriptor::Text)) }] }] }, constraints: alloc::vec![] },
super::NamedType { name: "RenderOptions".into(), shape: super::TypeShape::Record { fields: alloc::vec![super::FieldDescriptor { name: "parallel".into(), ty: super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.doc.html".into(), revision: 1, name: "ParallelMode".into() }) }] }, constraints: alloc::vec![] },
super::NamedType { name: "RenderedFragment".into(), shape: super::TypeShape::Record { fields: alloc::vec![super::FieldDescriptor { name: "documentDigest".into(), ty: super::TypeDescriptor::Bytes },super::FieldDescriptor { name: "options".into(), ty: super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.doc.html".into(), revision: 1, name: "RenderOptions".into() }) },super::FieldDescriptor { name: "markup".into(), ty: super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.markup".into(), revision: 1, name: "HtmlRequest".into() }) },super::FieldDescriptor { name: "origins".into(), ty: super::TypeDescriptor::List(alloc::boxed::Box::new(super::TypeDescriptor::Named(super::TypeRef { package: "nepl3.doc.html".into(), revision: 1, name: "ElementOrigin".into() }))) }] }, constraints: alloc::vec![] }], operations: alloc::vec![] })
}
