import { catalog } from './katex/classes.mjs';
// Fixed-package asset inventory. Run after npm ci --prefix tools/audit/math.
// This inventories the reviewed distribution CSS; it is not a CSS sanitizer.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { KATEX_VERSION } from '../math/katex/render.mjs';
const root = new URL('../audit/math/node_modules/katex/', import.meta.url);
const output = new URL('../math/katex/assets.json', import.meta.url);
const packageInfo = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'));
if (packageInfo.name !== 'katex' || packageInfo.version !== KATEX_VERSION) throw Error('unexpected KaTeX package');
const lock = JSON.parse(readFileSync(new URL('../audit/math/package-lock.json', import.meta.url), 'utf8'));
const css = readFileSync(new URL('dist/katex.min.css', root), 'utf8');
const fonts = [...css.matchAll(/url\(([^)]+)\)/g)].map(match => match[1]);
if (!fonts.length || fonts.some(path => !/^fonts\/KaTeX_[A-Za-z0-9-]+\.(woff2?|ttf)$/.test(path))) throw Error('review CSS font references');
const entries = [
  ['dist/katex.min.css', 'katex.min.css', 'text/css'],
  ['LICENSE', 'LICENSE', 'text/plain'],
  ...[...new Set(fonts)].sort().map(path => [`dist/${path}`, path,
    path.endsWith('.woff2') ? 'font/woff2' : path.endsWith('.woff') ? 'font/woff' : 'font/ttf']),
].map(([source, path, mime]) => {
  const bytes = readFileSync(new URL(source, root));
  return { source, path, mime, bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') };
});
const header = {
  version: KATEX_VERSION,
  packageIntegrity: lock.packages['node_modules/katex'].integrity,
};
const text = JSON.stringify(header, null, 2).slice(0, -2) + ',\n  "files": [\n' +
  entries.map(entry => `    ${JSON.stringify(entry)}`).join(',\n') + '\n  ]\n}\n';
const rustOutput = new URL('../src/doc/math/assets/pins.rs', import.meta.url);
const rust = '// Generated by tools/generate/katex.mjs from the fixed package inventory.\n' +
  `pub(super) const VERSION: &str = ${JSON.stringify(KATEX_VERSION)};\n` +
  '#[rustfmt::skip]\npub(super) const PINS: &[super::Pin] = &[\n' +
  entries.map(entry => `    super::Pin { source: ${JSON.stringify(entry.source)}, path: ${JSON.stringify(entry.path)}, mime: ${JSON.stringify(entry.mime)}, bytes: ${entry.bytes}, digest: [${[...Buffer.from(entry.sha256, 'hex')].join(',')}] },`).join('\n') + '\n];\n';
const classCatalog = catalog(css, KATEX_VERSION);
const classText = JSON.stringify(classCatalog, null, 2) + '\n';
const classIdentity = createHash('sha256').update(classText).digest('hex');
const hexBytes = value => [...Buffer.from(value, 'hex')].join(',');
const classRust = '// Generated by tools/generate/katex.mjs; fixed reviewed CSS/producer catalog.\n' +
  `pub(super) const VERSION: &str = ${JSON.stringify(KATEX_VERSION)};\n` +
  `#[rustfmt::skip]\npub(super) const CSS_DIGEST: [u8;32] = [${hexBytes(classCatalog.css_sha256)}];\n` +
  `#[rustfmt::skip]\npub(super) const IDENTITY: [u8;32] = [${hexBytes(classIdentity)}];\n` +
  '#[rustfmt::skip]\npub(super) const CLASSES: &[&str] = &[\n' + classCatalog.classes.map(value => `    ${JSON.stringify(value)},`).join('\n') + '\n];\n';
const outputs = [[output, text], [rustOutput, rust],
  [new URL('../math/katex/classes.json', import.meta.url), classText],
  [new URL('../src/doc/math/assets/catalog.rs', import.meta.url), classRust]];
if (process.argv.length === 3 && process.argv[2] === '--write') {
  for (const [path, content] of outputs) writeFileSync(path, content);
} else if (process.argv.length === 2) {
  for (const [path, content] of outputs) {
    if (readFileSync(path, 'utf8') !== content) throw Error('KaTeX inventory changed; review the fixed package before --write');
  }
} else throw Error('usage: node tools/generate/katex.mjs [--write]');
