"""Generate exhaustive adapter dispatch from the existing normative form catalog."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def outputs(root=ROOT):
    categories=json.loads((root/"design/forms.json").read_text(encoding="utf-8"))["categories"]
    result={}
    for host,path in [(True,"tools/src/bootstrap/generated.rs"),(False,"crates/languages/grammar/core/src/lower/generated.rs")]:
        lines=["// Generated by tools/generate/lowering.py from design/forms.json. Do not edit.","use super::*;","#[rustfmt::skip]","impl Adapter<'_> {"]
        if host: lines += ["pub(super) fn constructor(&mut self, value:&Value)->Result<NodeKind,SeedError>{", "match (self.string(value,\"category\")?,self.string(value,\"kind\")?) {"]
        else: lines += ["pub(super) fn constructor(&mut self, node:&SyntaxNode, form:&Form)->Result<NodeKind,LowerError>{", "match (form.category.as_str(),form.spelling.as_str()) {"]
        for category,body in categories.items():
            if not category.startswith("Grammar/"): continue
            for spelling,form in body["forms"].items():
                names=[f["name"] for f in form["fields"]]
                lines += [f'("{category if host else category.split("/")[1]}","{form["kind"] if host else spelling}")=>{{']
                if host: lines += [f'self.head(value,"{spelling}")?;',"self.fields(value,&["+",".join(json.dumps(n) for n in names)+"])?;"]
                fields=[]
                for field in form["fields"]:
                    read=field["read"];name=field["name"];native="r#"+name if name in {"type","ref","self"} else name
                    args=f'value,"{name}"' if host else f'node,form,"{name}"'
                    if isinstance(read,dict): method="list";args+=",Category::"+read["list"].split("/")[1]
                    elif read.startswith("@"): method=read[1:].lower()
                    else: method="node";args+=",Category::"+read.split("/")[1]
                    fields.append(f'{native}:self.{method}({args})?')
                native="SelfSelector" if form["kind"]=="Self" else form["kind"]
                lines += ["Ok(NodeKind::"+native+("{"+",".join(fields)+"}" if fields else "")+")},"]
        lines += ["_=>Err("+("SeedError::Shape" if host else "LowerError::Shape")+")", "}", "}","}"]
        result[root/path]="\n".join(lines)+"\n"
    return result

def update(write=False):
    for path,text in outputs().items():
        if write:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding="utf-8",newline="\n")
        elif not path.exists() or path.read_text(encoding="utf-8")!=text:raise SystemExit(f"Stale generated Grammar lowering: {path}")
if __name__=="__main__":
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument("--write",action="store_true");update(parser.parse_args().write)
