// Generated by tools/generate/katex/modules.mjs. Do not hand edit.
pub(super) const IDENTITY: &str =
    "b60a560dda687543da3dadd4676b8af9ae0518915f0fe80e55e46a288185cc98";
pub(super) const LOADER: &str = "fixed-owned-esm/1";
pub(super) const VERSION: &str = "0.18.7";
pub(super) const BYTES: u64 = 953744;
pub(super) const IDS: &[&str] = &[
    "entities/dist/esm/decode-codepoint.js",
    "entities/dist/esm/decode.js",
    "entities/dist/esm/escape.js",
    "entities/dist/esm/generated/decode-data-html.js",
    "entities/dist/esm/generated/decode-data-xml.js",
    "katex/dist/katex.mjs",
    "parse5/dist/common/doctype.js",
    "parse5/dist/common/error-codes.js",
    "parse5/dist/common/foreign-content.js",
    "parse5/dist/common/html.js",
    "parse5/dist/common/token.js",
    "parse5/dist/common/unicode.js",
    "parse5/dist/index.js",
    "parse5/dist/parser/formatting-element-list.js",
    "parse5/dist/parser/index.js",
    "parse5/dist/parser/open-element-stack.js",
    "parse5/dist/serializer/index.js",
    "parse5/dist/tokenizer/index.js",
    "parse5/dist/tokenizer/preprocessor.js",
    "parse5/dist/tree-adapters/default.js",
];
