// Fixed package-source closure inventory. Parsing imports is not execution.
// Run with --experimental-vm-modules --disable-warning=ExperimentalWarning.
import { SourceTextModule } from 'node:vm';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { posix } from 'node:path';
const root=new URL('../../audit/math/node_modules/',import.meta.url);
const entries={renderer:'katex/dist/katex.mjs',parser:'parse5/dist/index.js'};
const bare={'entities/decode':'entities/dist/esm/decode.js','entities/escape':'entities/dist/esm/escape.js'};
const expected={katex:'0.18.7',parse5:'8.0.0',entities:'6.0.1'};
const lock=JSON.parse(readFileSync(new URL('../../audit/math/package-lock.json',import.meta.url),'utf8'));
const packages=Object.entries(expected).map(([name,version])=>{
  const actual=JSON.parse(readFileSync(new URL(`${name}/package.json`,root),'utf8'));
  if(actual.name!==name||actual.version!==version)throw Error('review fixed package version');
  return {name,version,integrity:lock.packages[`node_modules/${name}`].integrity};
}).sort((a,b)=>a.name<b.name?-1:a.name>b.name?1:0);
function target(parent,specifier) {
  if(Object.hasOwn(bare,specifier))return bare[specifier];
  if(!specifier.startsWith('./')&&!specifier.startsWith('../'))throw Error(`unreviewed module request: ${specifier}`);
  if(/[\\%?#:]/.test(specifier))throw Error('noncanonical module request');
  const result=posix.normalize(posix.join(posix.dirname(parent),specifier));
  if(result.split('/')[0]!==parent.split('/')[0]||!result.endsWith('.js'))throw Error('module leaves reviewed package');
  return result;
}
const records=new Map(),pending=Object.values(entries);
while(pending.length) {
  const id=pending.pop();if(records.has(id))continue;
  const bytes=readFileSync(new URL(id,root));
  const source=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);
  const module=new SourceTextModule(source,{identifier:id});
  const imports=module.moduleRequests.map(request=>{
    if(request.phase!=='evaluation'||Object.keys(request.attributes).length)throw Error('unsupported import attributes/phase');
    const resolved=target(id,request.specifier);pending.push(resolved);
    return {specifier:request.specifier,target:resolved};
  });
  records.set(id,{id,format:'esm',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),imports});
}
const files=[...records.values()].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);
if(files.length!==20||files.reduce((n,f)=>n+f.bytes,0)!==953744)throw Error('review changed fixed source graph');
const data={format:'nepl3.katex.owned-source-graph/1',loaderPolicy:'fixed-owned-esm/1',packages,entries,files,
  scope:'Exact external package source/edge content only; trusted loader/bootstrap/runtime and remote authenticity are separate'};
const text=JSON.stringify(data,null,2)+'\n';
const identity=createHash('sha256').update('nepl3.katex.source-catalog/1\0').update(text).digest('hex');
const js='// Generated by tools/generate/katex/modules.mjs. Do not hand edit.\n'+
  'function freeze(value) { if(value && typeof value === "object") { for(const child of Object.values(value))freeze(child); Object.freeze(value); } return value; }\n'+
  `export const IDENTITY = ${JSON.stringify(identity)};\nexport const PINS = freeze(${JSON.stringify(data,null,2)});\n`;
const rust='// Generated by tools/generate/katex/modules.mjs. Do not hand edit.\n'+
  `pub(super) const IDENTITY: &str =\n    ${JSON.stringify(identity)};\n`+
  `pub(super) const LOADER: &str = ${JSON.stringify(data.loaderPolicy)};\n`+
  `pub(super) const VERSION: &str = ${JSON.stringify(expected.katex)};\n`+
  `pub(super) const BYTES: u64 = ${files.reduce((n,f)=>n+f.bytes,0)};\n`+
  `pub(super) const IDS: &[&str] = &[\n${files.map(f=>'    '+JSON.stringify(f.id)+',').join('\n')}\n];\n`;
const outputs=[[new URL('../../math/katex/modules.json',import.meta.url),text],[new URL('../../math/katex/node/module-pins.mjs',import.meta.url),js],[new URL('../../src/doc/math/display/process/reply/catalog.rs',import.meta.url),rust]];
if(process.argv.length===3&&process.argv[2]==='--write')for(const [path,data] of outputs)writeFileSync(path,data);
else if(process.argv.length===2)for(const [path,data] of outputs){if(readFileSync(path,'utf8')!==data)throw Error('fixed source graph drift');}
else throw Error('usage: node --experimental-vm-modules tools/generate/katex/modules.mjs [--write]');
