[package]
name = "external-composition-runtime"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
external-hello-language = { path = "../hello" }
nepl3-core = { path = "../../../crates/foundation/core" }
nepl3-suite = { path = "../../../crates/integration/suite" }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
